apiVersion: v2
name: wordpress
description: A Helm chart for Wordpress
version: 0.1.0

maintainers:
  - name: Your Name
    email: your.email@example.com

appVersion: "5.7.1"

dependencies:
  - name: mysql
    version: 8.0.25
    repository: https://charts.bitnami.com/bitnami

  - name: nginx-ingress
    version: 3.36.0
    repository: https://kubernetes.github.io/ingress-nginx

  - name: memcached
    version: 4.4.0
    repository: https://charts.bitnami.com/bitnami

  - name: redis
    version: 15.7.1
    repository: https://charts.bitnami.com/bitnami

values:
  image:
    repository: wordpress
    tag: 5.7.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: wordpress.example.com
        paths:
          - path: /(.*)
            backend:
              serviceName: wordpress
              servicePort: 80

  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteMany

  mysql:
    enabled: true
    auth:
      rootPassword: "password"
      password: "password"
    persistence:
      enabled: true
      size: 1Gi
      accessMode: ReadWriteMany
    primary:
      enabled: true

  memcached:
    enabled: true

  redis:
    enabled: true
    architecture: standalone
    password: "password"
    persistence:
      enabled: true
      size: 1Gi
      accessMode: ReadWriteMany

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
